version: '3.9'
networks:
  todo-network:
    driver: bridge
services:
  app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: todolist-container
    build:
      context: .
      dockerfile: TodoList/Dockerfile
    ports:
      - '80:80'
    networks:
      - todo-network
    depends_on:
      - todolist-db
  todolist-db:
    container_name: todolist-db-container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: TodoListDb
    ports:
      - "5432:5432"
    networks:
      - todo-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
